[workspace]
members = ["composer/", "filters/"]
resolver = "2"

[workspace.dependencies]
miette = { version = "5.8.0", features = ["fancy"] }
pandoc_types = "0.5.0"
serde = "1.0.158"
serde_json = "1.0.94"
heck = "0.4.1"
itertools = "0.10.5"
camino = { version = "1.1.4", features = ["serde1"] }
